MEDICAL_CATEGORIES = [
    "Health Care Activity",
    "Organism Function",
    "Disease or Syndrome",
    "Finding",
    "Population Group",
    "Cell",
    "Organism Attribute",
    "Biomedical Occupation or Discipline",
    "Biologically Active Substance",
    "Organic Chemical",
    "Therapeutic or Preventive Procedure",
    "Body Substance",
    "Patient or Disabled Group",
    "Laboratory Procedure",
    "Family Group",
    "Element, Ion, or Isotope",
    "Food",
    "Gene or Genome",
    "Molecular Biology Research Technique",
    "Nucleotide Sequence",
    "Clinical Attribute",
    "Amino Acid Sequence",
    "Biomedical or Dental Material",
    "Neoplastic Process",
    "Cell Component",
    "Diagnostic Procedure",
    "Age Group",
    "Anatomical Structure",
    "Body Location or Region",
    "Pharmacologic Substance",
    "Physiologic Function",
    "Body Part, Organ, or Organ Component",
    "Anatomical Abnormality",
    "Body System",
    "Mental or Behavioral Dysfunction",
    "Pathologic Function",
    "Congenital Abnormality",
    "Human",
    "Tissue",
    "Laboratory or Test Result",
    "Medical Device",
    "Biologic Function",
    "Immunologic Factor",
    "Virus",
    "Sign or Symptom",
    "Organ or Tissue Function",
    "Chemical Viewed Structurally",
    "Molecular Function",
    "Antibiotic",
    "Research Device",
    "Cell Function",
    "Genetic Function",
    "Experimental Model of Disease",
    "Eukaryote",
    "Embryonic Structure",
    "Body Space or Junction",
    "Bacterium",
    "Organism",
    "Cell or Molecular Dysfunction",
    "Indicator, Reagent, or Diagnostic Aid",
    "Nucleic Acid, Nucleoside, or Nucleotide",
    "Hazardous or Poisonous Substance",
    "Inorganic Chemical",
    "Injury or Poisoning",
    "Enzyme",
    "Receptor",
    "Hormone",
    "Chemical Viewed Functionally",
    "Amino Acid, Peptide, or Protein",
    "Vitamin",
    "Chemical",
    "Acquired Abnormality",
    "Molecular Sequence",
    "Fully Formed Anatomical Structure",
]
